### ISSUE TITLE
Show data at multiple time scales

### ISSUE THREAD

**Issue by DillonJ** [node-red/node-red-dashboard#360] opened 2018-02-27 09:12 UTC
Hi folks,
This is a great contribution. I'm using it to monitor and display temperatures using a number of ds18b20 sensors connected to a raspberry pi model B.

For each temperature (currently 3) I would like to show a history of the temps at different time scales. I.e. the last 5 minutes, the last hour and the last 12 hours. To do this, I set up 3 different charts and set the X-axis property to the last 5 minutes, 1 hour and 12 hours respectively. However, the x-axis scale is the same on all 3 charts. The only difference is that it only shows the last 5 minutes of data for the 5-min chart and the last hour for the last hour chart. I.e. you only see data to the extreme right of the graph. I would like, instead for the x axis range to also be limited to the last 5 minutes and last hour etc. To make sure I am getting this across property... my 5 minute graph has an x-axis scale of 12 hours but only shows data points at the extreme right. I don't seem to be able to control the scale of the x-axis but only the number of points that get displayed.

Is this possible, and if so, how do I accomplish this?

Thanks in advance.

**Comment by Paul-Reed** [comment] 2018-02-27 09:42
Git issues are really for reporting confirmed bugs (which need fixing).
If you make a post in either Slack or the Mailing list (as per the node-red user guide - https://nodered.org/docs/user-guide/) I'm sure you'll get some help in fixing your problem.

Paul

**Comment by wizbowes** [comment] 2018-02-27 16:42
This is a bug though.  It may be written as a question, but the bug is that the x-axis 'Last' parameter (Last 1 hour or last 60 points) is ignored.  I came here to report the same issues

Here are my settings:

![capture1](https://user-images.githubusercontent.com/25068983/36741429-010e2fa2-1bdd-11e8-9cf1-aba8636251e9.PNG)

And here's the output.  As you can see the x-axis  setting is not respecting the setting to limit to the last hour.

![image](https://user-images.githubusercontent.com/25068983/36741369-cdbad6fa-1bdc-11e8-8a84-b2070d14ce17.png)

**Comment by dceejay** [comment] 2018-02-27 16:50
you have multiple topics - it will only truncate a series when it get a new value in that series.
This is actually a duplicate of #342

**Comment by dceejay** [comment] 2018-02-27 22:25
I've pushed a possible fix to master (not npm) - you can try it by:

    cd ~/.node-red && npm i node-red/node-red-dashboard

**Comment by DillonJ** [comment] 2018-02-28 09:03
Hi folks,

I think the issue was with old data when you change the x-axis parameter. If you change the x-axis parameter to a value shorter than was it was and there was existing data, I think it continues to show the old data. However, if you clear the data to the chart by sending a null message and start clean, I think it functions correctly.

**Comment by dceejay** [comment] 2018-02-28 09:08
possibly. What I know is that it only updates / cleans up data for the topic (line colour) that arrives - so if nothing more arrives on that topic it never got a chance to clean up and remove those old points. I didn't want to iterate over every data point whenever any point arrives as that would suck performance wise for fast arriving data. So the proposed fix is to do an additional deep clean of any other topics one a minute.

**Closed** 2018-03-01 19:46 UTC
