### ISSUE TITLE
Chart working not correct

### ISSUE THREAD

**Issue by Vladyslav93** [node-red/node-red-dashboard#351] opened 2018-02-12 14:10 UTC
Hello.
Is it possible to explain me, maybe I am doing something wrong? Please have a look at the picture:
![image](https://user-images.githubusercontent.com/28342273/36100624-29ea183c-1007-11e8-86dc-4aa00312dafd.png)

So you can see that there are three graphs but the last one has really bad quality until the new data come.
Is it possible to fix this issue? Has someone the same?

Best Regards

**Comment by dceejay** [comment] 2018-02-12 14:15
Duplicate of #302 
(does sending new data - or a screen refresh fix it (temporarily) ?

**Closed by dceejay** 2018-02-12 14:15 UTC

**Comment by Vladyslav93** [comment] 2018-02-12 14:23
Yes, the new data will fix it. But the problem that the new data can come not that fast.

**Comment by dceejay** [comment] 2018-02-12 15:26
indeed - needs looking at - re-opened the other issue (as that came first). Thanks
