### ISSUE TITLE
Bug: resets dashboard tab on deploy

### ISSUE THREAD

**Issue by toddmedema** [node-red/node-red-dashboard#187] opened 2017-03-11 17:58 UTC
(note: tried asking as a question in the Google Group, but apparently you have to apply for membership, so I'm going to ask / report it here, and it can be moved if there's a more appropriate spot for it)

Annoying bug: whenever you hit "deploy" in node red, it resets the dashboard tab to tab 0 on ALL devices with node red open. Which is terrible, because we have multiple tablets around the house to control different parts of the house, each with their own tab... each of which lose their place on a deploy.

It might make sense to reset to tab 0 if the tab it was on no longer exists, but I'd think the default behavior should be to refresh the existing tab.

**Comment by knolleary** [comment] 2017-03-11 18:01
Hi, thanks for reporting. Agreed that would be a desirable behaviour.


The​ main project Google group does require you to be a member, but membership is just clicking the button... no approvals needed.

**Comment by dceejay** [comment] 2017-03-11 18:18
It's not a bug - it's the way it works. 
Nothing holds state of any clients so when the main flow is redeployed all state is reset. 
Not sure if partial deploy mode would help ?

probably makes most sense in the context of logged in users - rather than multiple browsers, but given you have static devices it may be possible to think of a scheme based on localStorage.

**Comment by toddmedema** [comment] 2017-03-11 18:29
Looks like a partial deploy does preserve the tab state. But, would still love to see this with overall deploys too :)

**Comment by dceejay** [comment] 2017-08-29 17:51
if the browser is open on tab #1 we don't force it back to #0
closing now as I think it does as requested (at least for me)

**Closed by dceejay** 2017-08-29 17:51 UTC
Labels: enhancement

**Comment by Paul-Reed** [comment] 2017-08-29 18:05
It happens here too.
Deploying changes always takes me back to tab #0.

**Comment by dceejay** [comment] 2017-08-29 18:06
which browser ? OS ? dashboard version etc ?

**Comment by Paul-Reed** [comment] 2017-08-29 18:18
Chrome browser Version 60.0.3112.101 (Official Build) (64-bit)
OS Raspbian GNU/Linux 8 (jessie)
Hardware - Raspberry Pi 3
Dashboard version - current git master

![tab](https://user-images.githubusercontent.com/973580/29837004-d4c6bc0c-8cee-11e7-947e-a270de1ed262.gif)

**Comment by underwoodblog** [comment] 2017-08-29 18:27
Have you tried a other Browser. One of your many extensions may be the cause. Maby try in an incognito window.

**Comment by dceejay** [comment] 2017-08-29 18:46
Likewise here all is fine...

http://recordit.co/JbjCCTI7Ju

and same behaviour on my Pi 3

**Comment by Paul-Reed** [comment] 2017-08-29 18:51
Strange... but not a big issue (for me), hence I didn't raise it.
