### ISSUE TITLE
Style Settings LOST

### ISSUE THREAD

**Issue by ma-gu-16** [node-red/node-red-dashboard#488] opened 2019-04-16 14:50 UTC
If i change the following settings under Angular Theme, it will be deleted after +/-24 Hours to the following default settings.

i try to set dark theme und grey-glue color scheme.

 https://github.com/node-red/node-red-dashboard/issues 
![56153406-5b2eef80-5fb6-11e9-9f32-00383e546230](https://user-images.githubusercontent.com/22169074/56219625-5c6c2500-6067-11e9-867a-3c5553a51d42.PNG)

NodeREd Version 0.20.5

**Comment by dceejay** [comment] 2019-04-16 15:07
How are you running Node-RED ? Which OS? Which version of Dashboard ?

**Comment by ma-gu-16** [comment] 2019-04-17 11:04
Hi,

i think all the current versions. its part of a bundle. running on raspberry pi 3
"redmatic": "4.1.2",
   "nodejs": "10.15.3",
   "ain2": "3.0.0",
   "node-red": "0.20.5",
   "node-red-contrib-modbus": "4.1.3",

hope this is the versions?

**Comment by dceejay** [comment] 2019-04-20 11:11
Hi - not suite sure how or why this could reset. I have set a version up locally as you have at it remains on that theme for several days now. I don't know whether redmatic may have something to do with it, but I'd be surprised - maybe @hobbyquaker can comment if he sees this.

The only way it should change is if there is a re-deploy for some reason. Is there anything else you have or may know that may help us to recreate the problem ?

**Comment by hobbyquaker** [comment] 2019-04-20 17:16
@dceejay where are these settings stored? are they part of the flows json?

**Comment by dceejay** [comment] 2019-04-20 17:28
yes - should be.

**Comment by hobbyquaker** [comment] 2019-04-20 17:48
hmm... i have no clue. I think it's very unlikely that the flows json gets reverted to an older state...

**Comment by dceejay** [comment] 2019-04-20 18:28
yeah - hmm - ok - will let it simmer and think some more.

**Comment by ma-gu-16** [comment] 2019-05-09 11:24
any solutions for this ?

**Comment by dceejay** [comment] 2019-05-09 11:26
I have yet to be able to recreate it so can't yet track it down.

**Comment by Vinisz** [comment] 2019-05-12 06:11
I have the same issue, running latest node-red in docker on synology

**Comment by dceejay** [comment] 2019-05-12 11:18
great - but until I can find a way to re-create this (or someone shows me how) then I won't be able to debug it.  (unless they can debug it and send a pull request.)

**Comment by mereshow** [comment] 2019-05-19 10:36
I also have the same issue several times a day.
I think it usually happens when an warning or error occur, for instance having an empty group, but I am unable to reproduce it. I will post the steps if I can.

**Comment by justinSCS** [comment] 2019-07-24 14:09
I am also having this problem.  I exported my flow as a json object and am not seeing a "ui_base" anywhere in the file.  Could this be causing the issue?

**Comment by dceejay** [comment] 2019-10-13 10:04
no further info - or help to debug - closing for now.

**Closed by dceejay** 2019-10-13 10:04 UTC
Labels: OK to close ?, more info required
