### ISSUE TITLE
Divs overlapping on Screen

### ISSUE THREAD

**Issue by jahuang0824** [node-red/node-red-dashboard#69] opened 2016-10-07 07:31 UTC
Initially, I have 6 groups on the dashboard and it looks good. 
![1](https://cloud.githubusercontent.com/assets/13759799/19180880/c3941c80-8c9b-11e6-8523-04d35bb04a5c.jpg)

Then, I changed the group order by moving "Software Information" to first place.
![3](https://cloud.githubusercontent.com/assets/13759799/19181158/b2da6e6a-8c9d-11e6-82f4-b506b84aa0f1.jpg)

After flow deployment, the second group ,"PoE-PoE 1", is overlapped by final group "GSensor-Data".
![2](https://cloud.githubusercontent.com/assets/13759799/19181037/ea756556-8c9c-11e6-95eb-c4b13495296e.jpg)

This looks like the same as [issue #42](https://github.com/node-red/node-red-dashboard/issues/42) and should be fixed in node-red-dashboard v2.0.1.

My software environment is:
  - nodejs v4.5.0
  - Node-RED v0.14.2
  - node-red-dashboard v2.0.2
  - Chrome v53.0.2785.143

All ui nodes are auto sized.

Jahuang

**Comment by dceejay** [comment] 2016-10-07 07:39
I believe this is a duplicate of #57 - which should be fixed in 2.0.3 - which is in master but not yet pushed to npm -  to try it...    npm i node-red/node-red-dashboard

**Comment by jahuang0824** [comment] 2016-10-07 08:10
Thanks for the response.
This issue is solved in the latest master code.

**Closed** 2016-10-07 08:19 UTC
