### ISSUE TITLE
Chart working not correct

### ISSUE THREAD

**Issue by Vladyslav93** [node-red/node-red-dashboard#353] opened 2018-02-14 09:24 UTC
The problem from post #351 :

The graph has bad quality. All the information from the #351 

Thanks.

**Comment by knolleary** [comment] 2018-02-14 09:26
#351 was closed as a duplicate of #302 

Why have you opened this issue?

**Comment by Vladyslav93** [comment] 2018-02-14 09:26
Because the owner told that I need to re-open. And the post #302 did not help me.

**Comment by knolleary** [comment] 2018-02-14 09:28
No, @dceejay said he would reopen #302 which he has done. If you don't think #302 is related despite @dceejay's comments, then we can reopen #351. There is no need to have a duplicate issue like this.

**Closed by knolleary** 2018-02-14 09:28 UTC

**Comment by Vladyslav93** [comment] 2018-02-14 10:07
Ok, sorry
