### ISSUE TITLE
ui_button optional text/icon color ont working

### ISSUE THREAD

**Issue by Bond246** [node-red/node-red-dashboard#671] opened 2021-01-18 14:10 UTC
### What are the steps to reproduce?

Generating a new ui_button and define a background-color an optional text-color.

### What happens?

Background-Color changes as defined.
Text-Color stays white

### What do you expect to happen?

Text-Color should be like defined.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.26.2
- [ ] Node-RED version: 2.2.7
- [ ] node.js version: like in docker
- [ ] npm version: like in docker
- [ ] Platform/OS: docker / ubuntu
- [ ] Browser: edge(chromium, windows), firefox (latest, windows + android), chrome (android)

**Comment by dceejay** [comment] 2021-01-18 15:20
Duplicate of #670 
already fixed in master
just not on npm yet

**Closed by dceejay** 2021-01-18 15:20 UTC
Labels: duplicate
