### ISSUE TITLE
Calling UI with multiple tabs with base URL crashes Node

### ISSUE THREAD

**Issue by TheOriginalMrWolf** [node-red/node-red-dashboard#310] opened 2017-11-19 02:15 UTC
Hi,

Have a UI with 3 tabs, first tab with a single chart, plotting two series, updated once every five minutes, storing last 3 hours.

- Node-RED version: v0.17.5
- Node.js  version: v8.6.0
- Running DietPi distro on Linux 4.9.61-v7+ arm LE
- Dashboard version 2.6.0 started at /ui

If you call the UI with a base URL - "<mypi>:1880/ui" instead of "<mypi>:1880/ui/#/0" - then node red crashes out entirely and needs to be restarted.

Syslog says:

- TypeError: Cannot read property 'header' of undefined
- at Socket.<anonymous> (/mnt/dietpi_userdata/node-red/node_modules/node-red-dashboard/ui.js:336:35)
- at emitOne (events.js:115:13)
- at Socket.emit (events.js:210:7)
- at /mnt/dietpi_userdata/node-red/node_modules/socket.io/lib/socket.js:503:12
- at _combinedTickCallback (internal/process/next_tick.js:131:7)
- at process._tickCallback (internal/process/next_tick.js:180:9)
- node-red.service: main process exited, code=exited, status=1/FAILURE

So had a look at node-red-dashboard/ui.js and changed line 336 from:
```
name = menu[index].header === undefined ? menu[index].name : menu[index].header;
```
to:
```
name = (typeof menu[index].header === 'undefined') ? menu[index].name : menu[index].header;
```
.... well, that didn't work... so tried
```
name = (menu[index].hasOwnProperty("header") && typeof menu[index].header !== 'undefined') ? menu[index].header : menu[index].name;
```

...and that worked (so far).  Yay me, but what do I know, I'm no programmer...

Can someone who knows what they're doing please have a look at this?

Cheers!

**Comment by TheOriginalMrWolf** [comment] 2017-11-19 20:57
So.... that worked fine for almost 24 hours - and made node _much_ more stable - but then a _new_ error...
```
 - [red] Uncaught Exception:
 - TypeError: Cannot read property 'hasOwnProperty' of undefined
  at Socket.<anonymous> (/mnt/dietpi_userdata/node-red/node_modules/node-red-dashboard/ui.js:336:36)
```
Lol.

Looks like maybe the index check isn't quite achieving what the author intended...

Smashed in a quick & dirty catchall to at least stop node-red from exploding...
```
            try {
              if (tl > 0 && index <= tl) {
                  name = (menu[index].hasOwnProperty("header") && typeof menu[index].header !== 'undefined') ? menu[index].header : menu[index].name;
              }
              ev.emit("changetab", index, name, socket.client.id, socket.request.connection.remoteAddress);
            }
            catch(err) {
              log.error("Error handling ui-change event: " + err.message);
            }
```

On the plus side - I can now replicate the issue every time!

In Safari, if I call the URL "<mypi>:1880/ui" then I hit the exception.  If the URL is "<mypi>:1880/ui/#/0" then there's never a problem! :)

Seriously - can someone who _actually_ knows what they're doing have a look please?

Thanks!

**Comment by TheOriginalMrWolf** [comment] 2017-11-19 21:39
Made some edits after I worked out that the issue is caused purely by which URL is called, regardless of platform or browser.

**Comment by dceejay** [comment] 2017-11-19 21:43
What is typeof (and value) of `index` at that point ?

**Comment by TheOriginalMrWolf** [comment] 2017-11-20 09:13
Changed the log.error to:
```
log.error("Error handling ui-change event: " + err.message + ".  Index: [typeof:" + typeof index + ",  value:" + index + "]");
```
Got:
```
[error] Error handling ui-change event: Cannot read property 'hasOwnProperty' of undefined.  Index: [typeof:object,  value:null]
```

Let me know if you'd like anything else collected.  Mind you, just calling the base url (eg: http://hostname:1880/ui) should do it for you.

**Comment by dceejay** [comment] 2017-11-20 09:31
still working fine here so I must be missing a step to break it properly.
Can you try the "fix" above ? ie add the !isNaN check into the if.
Though I think the cause is actually over in main.js around line 287/288 - the finishloading() should be inside the if just above.

**Comment by dceejay** [comment] 2017-11-28 23:34
does the latest updates in 2.6.3-beta on master fix this ?

**Comment by dceejay** [comment] 2017-12-03 23:30
I think this is now fixed - so going to close. Please re-open if not

**Closed by dceejay** 2017-12-03 23:30 UTC
