### ISSUE TITLE
Disabling a button triggers its payload

### ISSUE THREAD

**Issue by Hugobox** [node-red/node-red-dashboard#211] opened 2017-04-20 13:45 UTC
In the latest Dashboard 2.3.8, disabling a button also triggers its payload. That wasn't the behavior in 2.3.5. 

`[
    {
        "id": "5d9006a1.0376f8",
        "type": "inject",
        "z": "bee780b1.7fabf",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 449,
        "y": 713,
        "wires": [
            [
                "4ca9d7ff.1b9948"
            ]
        ]
    },
    {
        "id": "a929cf6b.ca69e",
        "type": "ui_button",
        "z": "bee780b1.7fabf",
        "name": "",
        "group": "897e31a4.982b3",
        "order": 0,
        "width": 0,
        "height": 0,
        "label": "button",
        "color": "",
        "bgcolor": "",
        "icon": "",
        "payload": "bob",
        "payloadType": "str",
        "topic": "",
        "x": 780,
        "y": 719,
        "wires": [
            [
                "5c9ea479.023b5c"
            ]
        ]
    },
    {
        "id": "4ca9d7ff.1b9948",
        "type": "change",
        "z": "bee780b1.7fabf",
        "name": "",
        "rules": [
            {
                "t": "delete",
                "p": "payload",
                "pt": "msg"
            },
            {
                "t": "set",
                "p": "enabled",
                "pt": "msg",
                "to": "false",
                "tot": "bool"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 612,
        "y": 715,
        "wires": [
            [
                "a929cf6b.ca69e"
            ]
        ]
    },
    {
        "id": "5c9ea479.023b5c",
        "type": "debug",
        "z": "bee780b1.7fabf",
        "name": "",
        "active": true,
        "console": "false",
        "complete": "false",
        "x": 914,
        "y": 722,
        "wires": []
    },
    {
        "id": "897e31a4.982b3",
        "type": "ui_group",
        "z": "",
        "name": "Show info",
        "tab": "462cca59.b2b1f4",
        "order": 1,
        "disp": true,
        "width": "12"
    },
    {
        "id": "462cca59.b2b1f4",
        "type": "ui_tab",
        "z": "",
        "name": "Show Status",
        "icon": "fa-eye",
        "order": 1
    }
]`

**Comment by dceejay** [comment] 2017-04-20 14:53
indeed - sort of... previously you could not passthrough the msg properties at all - which was not consistent with normal node behaviour - so 17ec750c2c55f782e9122e476c6a7bef23aab610 changed this to be more consistent... however yes - if there is actually no payload then there is little point in passing it through (or forcing it to be generated) - so I think not outputting if there is no payload would be sensible.

**Comment by Hugobox** [comment] 2017-04-21 14:00
Would adding the checkbox "if msg arrives on input, pass through to output"
work in that case?

Hugo

**Comment by Paul-Reed** [comment] 2017-04-23 17:48
This has now broken my flow!
What is wrong is allowing no payload to trigger a flow?
I was using an inject node to trigger a flow every 15 minutes, and feeding that into a button node (to enable the flow to be run on demand via the dashboard) but which is now broken.
Other nodes a blank payload.

**Comment by knolleary** [comment] 2017-04-23 18:05
Yeah... I'm :-1: on this change... It will definitely break existing flows needlessly, regardless of where you stand on the 'rightness' of it.

**Comment by dceejay** [comment] 2017-04-23 18:38
how did you configure the inject node to send a msg with no payload property ?

**Comment by Paul-Reed** [comment] 2017-04-23 20:06
It was just injecting a blank string to initiate the flow, and worked just
fine.
What's peed me, is that I'm 70 miles from home in a hotel, and just spent
an hour on a 5" mobile with dodgy Wi-Fi, trying to find why the dashboard
isn't functioning...
But that's more my problem than yours - I shouldn't have updated dashboard
without checking it afterwards!!

**Comment by dceejay** [comment] 2017-04-23 20:11
Major apologues, but a blank string will still work as before so must be something else.

**Comment by Paul-Reed** [comment] 2017-04-23 20:51
Not working here, tried both triggering the inject via the editor, also via
it's cron schedule with a blank string, yet using the button via the
dashboard does initiate the flow.

Inject node > button node > rest of flow

I'm back home tomorrow so I can check more thoroughly...

On 23 Apr 2017 21:11, "Dave Conway-Jones" <notifications@github.com> wrote:

Major apologues, but a blank string will still work as before so must be
something else.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/node-red/node-red-dashboard/issues/211#issuecomment-296485176>,
or mute the thread

**Comment by Paul-Reed** [comment] 2017-04-24 10:20
OK back home...

Please try the flow below, it's just a inject node & a button node, plus a couple if debugs.
This has worked fine for a number of weeks since https://github.com/node-red/node-red-dashboard/commit/17ec750c2c55f782e9122e476c6a7bef23aab610, but stopped upon @dceejay 's commit https://github.com/node-red/node-red-dashboard/commit/ea5129083adf70f8ad0922ba5ca0403a99f80f9a (I can tell by the time recorded by my dashboard - last update time)
It appears that a blank 'string' input does not now pass through the button node, which is not consistent with other node actions, and stops the flow.

```[{"id":"68c38721.d163e8","type":"inject","z":"6eb37a1d.ee8f34","name":"Every 15 mins","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"*/1 0-23 * * *","once":false,"x":166,"y":151,"wires":[["e2f83286.86a2f","4d9fa773.a58728"]]},{"id":"e2f83286.86a2f","type":"ui_button","z":"6eb37a1d.ee8f34","name":"Dash Refresh","group":"8880d363.148ac","order":17,"width":"1","height":"1","label":"","color":"","bgcolor":"","icon":"fa-refresh fa-2x","payload":"","payloadType":"str","topic":"","x":351.33001708984375,"y":111.1099853515625,"wires":[["599d8e4f.01951"]]},{"id":"599d8e4f.01951","type":"debug","z":"6eb37a1d.ee8f34","name":"","active":true,"console":"false","complete":"false","x":523,"y":112,"wires":[]},{"id":"4d9fa773.a58728","type":"debug","z":"6eb37a1d.ee8f34","name":"","active":true,"console":"false","complete":"false","x":524,"y":150,"wires":[]},{"id":"8880d363.148ac","type":"ui_group","z":"","name":"Thermostat demo","tab":"db58ad1a.e37a8","order":2,"disp":true,"width":"6"},{"id":"db58ad1a.e37a8","type":"ui_tab","z":"","name":"Test stuff","icon":"dashboard"}]```

**Comment by Paul-Reed** [comment] 2017-04-24 10:28
In fact... I'm struggling to now pass anything through the button node; a payload value (string or number), or a topic.

**Comment by dceejay** [comment] 2017-04-24 12:19
Aha - got it.  yes. Thanks. an earlier fix was being "too helpful"... and tidying up "something we later relied on in court"... or something like that .  Back on master.
Apologies again.

**Comment by dceejay** [comment] 2017-04-30 17:23
So - reviewing this change - the fix has broken a lot of other things (dropping msgs without payload was bad... as the text and template nodes could also render things other that payload...)

Now thinking that maybe just adding the "allow input passthru" flag like on other nodes would just be the simpler option.

**Comment by Paul-Reed** [comment] 2017-04-30 17:37
Sounds a flexible way forward.
Presumably the default setting would be disallow?
If so, it may break some existing flows, but easy enough to resolve (so long as users are aware of the change)

**Comment by knolleary** [comment] 2017-04-30 17:39
IMHO, the default must be the existing behaviour, or done so that existing flows continue to work without intervention.

We do not knowingly breaking flows.

**Comment by dceejay** [comment] 2017-04-30 17:45
well - the default for that flag on all other nodes so far is to allow passthru...
until recently the button did not allow any passthru at all - the ability to allow passthru was added  in 2.3.6 which caused this issue.  
So should the default be consistent with other nodes - or with previous behaviour ? 
(I'm going to guess existing behaviour - i.e. don't through)

**Comment by Paul-Reed** [comment] 2017-04-30 18:03
Pass-through by default seems the safest option, especially if that's the default behaviour for other nodes too.

**Comment by dceejay** [comment] 2017-04-30 19:09
Well, actually I think the opposite :-) pre 2.3.6 behaviour was not to pass through, and the issue is calling that out.

**Comment by Paul-Reed** [comment] 2017-04-30 19:45
Well passthrough was enabled in git almost 8 weeks ago, so regardless whichever you choose it may affect users in either camp.
IMO, either way, any resultant problems can be easily sorted, so not a big issue - go with either.
...but it would be nice to have a common node protocol, so users can expect the same default behavior whichever node they use.

**Comment by dceejay** [comment] 2017-05-03 22:39
pushed to git master as 2.3.10-beta

**Comment by dceejay** [comment] 2017-05-05 09:40
re closed by fed10a5f864a1f3bf9d7304ea19190dc530948f5

**Closed by dceejay** 2017-05-05 09:40 UTC
