### ISSUE TITLE
Subflows don't create separate items in the Layout

### ISSUE THREAD

**Issue by K-RAD** [node-red/node-red-dashboard#417] opened 2018-08-04 11:41 UTC
I have a subflow that includes a switch+slider.

When I add multiple subflows, all items show up on the actual dashboard, but in the Layout / Tabs & Links it shows the switch+slider only once, so I can't rearrange.

- [ ] Node-RED-Dashboard version: 2.9.6
- [ ] Node-RED version: 0.18.7
- [ ] node.js version: 8.11.3
- [ ] npm version: 5.6.0
- [ ] Platform/OS: Windows
- [ ] Browser: Chrome

**Comment by knolleary** [comment] 2018-08-04 11:42
Yes. This is a known limitation of the dashboard. Nothing is going to change about this anytime soon

**Comment by dceejay** [comment] 2018-08-11 12:50
Closing as dupe of #66

**Closed by dceejay** 2018-08-11 12:50 UTC
Labels: duplicate
