### ISSUE TITLE
unable to pick a color on android

### ISSUE THREAD

**Issue by sleiner** [node-red/node-red-dashboard#117] opened 2016-12-16 15:29 UTC
## bug
The color picker widget is showing but I can not choose a new color on the phone.
Also live updates to the phone do not work.
On Firefox/Windows and Chrome/Windows, this all works fine.

## used version
- `node-red-dashboard`: 2.2.0
- `node-red`: 0.15.2
- `node.js`: 0.10.29

## reproduced on
 - Android 6.0.1 and Android 5.0.2, with both
    - Firefox 50.1.0
    - Chrome 55.0.2883.91

**Comment by hobbyquaker** [comment] 2016-12-16 16:13
I can reproduce this on Safari iOS too. On Safari macOS it works. (touch vs click?)

**Comment by Javierete** [comment] 2016-12-16 17:32
Hello!

I can confirm this behavior with Safari under iOS v10.1.1 BTW touching at random locations seems to change the colour picker value (and also outside colourpicker zone).

nodejs v4.7.0
node-red: 0.15.2
node-red-dashboard: 2.2.0

Sorry as I didn't had the time to test it under beta.

**Comment by dceejay** [comment] 2016-12-16 17:34
yes - ok got it... (seems to be a bug in underlying library - that has reappeared due to some change in Chrome...)

**Comment by helgrind** [comment] 2016-12-17 01:12
I think I've found a fix for the library, just waiting for them to respond 😄

**Comment by dceejay** [comment] 2016-12-17 11:56
For those willing to test ... I have pushed a built version to git-master with @helgrind patch included - this is not the final fix (hopefully the author will update soon) - but feel free to try it
   npm i node-red/node-red-dashboard
is the simple way to get it... (then refresh the browser a couple of times to flush your caches out).

**Comment by hobbyquaker** [comment] 2016-12-17 13:00
working fine on Safari/iOS.

**Comment by dceejay** [comment] 2016-12-19 18:44
Upstream issue being tracked here - https://github.com/ruhley/angular-color-picker/issues/133

**Comment by sleiner** [comment] 2016-12-19 18:59
Color picking and live updates are working on Android too :+1

**Comment by dceejay** [comment] 2016-12-24 13:44
Fixed by upstream version 2.7.2 - added to package.json  in  23c4422f2ddf6e42eb96f00ec28e3ecb13bf8910

**Closed by dceejay** 2016-12-24 13:44 UTC
Labels: upstream
