### ISSUE TITLE
Error during WebSocket handshake

### ISSUE THREAD

**Issue by javigf** [node-red/node-red-dashboard#381] opened 2018-04-11 12:42 UTC
Hi team.
I am facing an issue with my RPi3 with node ver 8.11.1 and node-red ver 0.18 . 
I reinstalled everything from scratch but , still the same issue. The rest of flows are fine. 
I dont know if log2ram might affect this somehow. 
The problem is with dashboard , when I goto http://192.168.1.172:1880/ui the browser shows a light blue blank screen with a title "undefined" . F12 shows the following. 
/uiuniversalModuleDefinition:3 WebSocket connection to 'ws://192.168.1.172:1880/ui/socket.io/?EIO=3&transport=websocket&sid=vUQ8Os6Nu-UXtT3EAAAB' failed: Error during WebSocket handshake: Unexpected response code: 400
n.doOpen @ universalModuleDefinition:3
app.min.js:467 Uncaught TypeError: Cannot read property '0' of undefined
    at Object.select (app.min.js:467)
    at i.connect.r.loaded (app.min.js:467)
    at n.<anonymous> (app.min.js:468)
    at n.emit (universalModuleDefinition:2)
    at n.onevent (universalModuleDefinition:3)
    at n.onpacket (universalModuleDefinition:3)
    at n.<anonymous> (universalModuleDefinition:3)
    at n.emit (universalModuleDefinition:2)
    at n.ondecoded (universalModuleDefinition:1)
    at s.<anonymous> (universalModuleDefinition:3)

Any comments please. Thanksa  lot in advance

**Comment by dceejay** [comment] 2018-04-12 08:52
Do you have anything between you and the Pi ? proxy, firewall., etc ?
any browser plugins that may be trying to upgrade you to https etc ?
What browser are you using ? on what OS ?

**Comment by javigf** [comment] 2018-04-12 11:56
No, there is nothing in between , I am at home. UTP cable connected (both RPi and local PC) to the same router. Tried with IE, Firefox, Chrome, and no changes , also I have an Ubuntu and W10 . Response is always the same one. I have not a clue... 
I dont know where and how to start debugging. Iam puzzled... Thanks a lot for your answer at least gave me some starting point.  Thanks again

**Comment by dceejay** [comment] 2018-05-08 21:03
this is odd - all the reading I can find points to things like a proxy, nginx, or some other thing in between you and node-red...

**Comment by dmerten** [comment] 2018-11-21 08:07
I have the same issue, using Node-Red in Docker-Container.  
I updated to the new version of dashboard and cleared  my dashboards as well. But the issue is still there. 
As far as i could debug it, the error is thrown in Line 99 main.js.
See https://github.com/node-red/node-red-dashboard/blob/master/src/main.js#L99

**Comment by dmerten** [comment] 2018-11-21 08:54
I have been done more research. In my case tabs and links are undefined when i getting data from the conect handler.
![image](https://user-images.githubusercontent.com/4471408/48829796-7719c680-ed73-11e8-8932-a0925efc4750.png)

**Comment by bratwiz** [comment] 2018-11-22 14:11
Something similar has happened to me as well. Everything was set up and working fine. I did add some new flows using the palette manager and reloaded node red each time afterwards and flipped around to make sure that everything continued to operate as it should. And afaik there were no issues and the dashboard looked like it was operating just find. 

For an unrelated reason I had to shutdown my system (raspberry pi3) and when I brought it back up again, all the flows were there, it connected to mqtt okay, but the dashboard tab was completely blank. I looked at the page source and it showed a stub window for the dashboard page but nothing visible. 

Just to be certain I went through and removed all of the flows that I had installed in the previous session and restarted the system. The dashboard is still blank. I pulled up the Chrome debugging tools and the console is showing the following errors (similar to the poster above) which is repeated over and over.

I am using Node Red v 0.19.5, and Node-Red-Dashboard v 2.11.0. I've included the list of installed nodes on down below. In the Node-Red-Dashboard section there is one item that has the Red '!' Triangle beside it but no information regarding what it's complaining about and nothing obvious that I can see in the node-red logs. They look fine and normal.

Any thoughts !?!?!?

Thanks!

John

**Javascript Console Log below:**

index.js:83 WebSocket connection to 'ws://10.100.1.141:1880/ui/socket.io/?EIO=3&transport=websocket&sid=iJqQn5gVvYjgeVbkAAAD' failed: Error during WebSocket handshake: Unexpected response code: 400

Uncaught TypeError: Cannot read property '0' of undefined
    at Object.select (app.min.js:467)
    at app.min.js:467
    at r.<anonymous> (app.min.js:468)
    at r.emit (index.js:83)
    at r.onevent (index.js:83)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
    at r.emit (index.js:83)
    at r.ondecoded (index.js:83)
    at a.<anonymous> (index.js:83)


**List of installed Nodes:**

node-red
0.19.5
node-red-contrib-ibm-watson-iot
0.2.8
node-red-contrib-play-audio
2.3.2
node-red-contrib-ui
1.2.20
node-red-dashboard
2.11.0
Type already registered
Type already registered
Type already registered
Type already registered
Type already registered
Type already registered
Type already registered
Type already registered
Type already registered
Type already registered
Type already registered
**_(Red '!' Triangle) Type already registered_**

node-red-node-email
0.1.29
node-red-node-feedparser
0.1.14
node-red-node-ledborg
0.0.21
node-red-node-pi-sense-hat
0.0.18
node-red-node-ping
0.0.15
node-red-node-random
0.1.2
node-red-node-rbe
0.2.4
node-red-node-serialport
0.6.8
node-red-node-smooth
0.1.0
node-red-node-twitter
1.1.4

**Comment by dceejay** [comment] 2018-11-22 18:48
"type already registered" means that you have two copies of dashboard nodes installed - This can often happen if you install the old version (node-red-contrib-ui) - or install one using sudo and one without using sudo... 

This is not the same as this issue.

**Comment by dceejay** [comment] 2018-12-20 22:51
closed by 5f6b111b02e51b342dd8281acf458cba9f18c24b

**Closed by dceejay** 2018-12-20 22:51 UTC
Labels: more info required

**Comment by corn98** [comment] 2019-06-12 12:40
Hi, 
I am facing with the same issue. When I open the dashboard it takes long time to load since it renders the CSS and includes mine CSS through ui-templates (added in the head section). 

When it loads, after a while i get these errors:

GET http://ip_address:1880/ui/socket.io/?EIO=3&transport=polling&t=MjBdDNl&sid=drJoLOlpBWeeb0gDAAAb 400 (Bad Request) index.js:83 
POST http://ip_address:1880/ui/socket.io/?EIO=3&transport=polling&t=MjBdEg5&sid=drJoLOlpBWeeb0gDAAAb 400 (Bad Request) index.js:83 
POST http://ip_address:1880/ui/socket.io/?EIO=3&transport=polling&t=MjBdEg5&sid=drJoLOlpBWeeb0gDAAAb 400 (Bad Request) index.js:83 

At index.js 83:

/**
 * Set the jitter
 *
 * @api public
 */

Backoff.prototype.setJitter = function(jitter){
  this.jitter = jitter;              //line 83
};


After this it tries to reload whole page but the result is the same of the first time, and it loops in this way infinitely.

The page have to manage roughly 1400 bytes of informations, sended by the flow. When I reduce data the problem doesn't occur but I've done other pages like this and I never had this problem.

Thanks in advance for any idea.


node
6.9.2
node-red
0.19.6
node-red-dashboard
2.15.4

**Comment by dceejay** [comment] 2019-06-12 13:00
The line you refer to is in the socket.io library. Can you identify the line in the dashboard code that is causing this ?

**Comment by corn98** [comment] 2019-06-12 13:26
Thanks for fast reply!

Yes, I know is the line in socket.io library, I referenced at it because only ones errors displayed in console are related at that line. I don't think library is wrong obviously, but error occurs there.

There aren't any other errors.

I attach the console view.

![console_view](https://user-images.githubusercontent.com/37583334/59354904-57a1b580-8d26-11e9-8ed2-474b103e9943.png)

Thanks for the support!
