### ISSUE TITLE
Numeric Input Node: Arrow disappears after clicking (on mobile device)

### ISSUE THREAD

**Issue by Harpau** [node-red/node-red-dashboard#501] opened 2019-05-21 07:21 UTC
On mobile devices, such as for example, iPhone or iPad, the behavior is as follows: When you click on one of the arrows to increase or decrease the input value, the arrow disappears. Clicking again on the same position will continue to work and change the input value. The arrow will reappear when I click on the menu button.
On a PC and with Chrome, however, the arrow disappears as soon as I move the mouse pointer over it.

**Comment by dceejay** [comment] 2019-05-21 09:45
This is actually a duplicate of #500. Button hover styling issue.

**Comment by dceejay** [comment] 2019-05-21 09:50
actually though related - may be different... but for me in chrome hovering does nothing unusual.

**Comment by dceejay** [comment] 2019-05-21 10:36
any chance you can try with latest update in master ? (to see if the button hover contrast fix helps)
Thanks

**Comment by Harpau** [comment] 2019-05-21 10:49
Happy to do that. How can I install it?

**Comment by dceejay** [comment] 2019-05-21 11:29
manually   

    cd ~/.node-red
    npm i node-red/node-red-dashboard

**Comment by Harpau** [comment] 2019-05-21 13:01
I have updated manually now: The Numeric Input Node behaves as before.
But the Switch Node works normal now.

**Comment by dceejay** [comment] 2019-05-21 13:05
which OS/hardware are you running on. Which browsers?

**Comment by Harpau** [comment] 2019-05-21 14:07
OS: iOS 12.2
Hardware: iPhone XS
Browser: Safari
Theme: Node-RED theme everywhere - Style: Light (Default)
Cache flushed: Yes
If I switch to Theme "Angular theme everywhere" the arrows don't disappear.
If I switch back to "Node-RED theme everywhere" the arrows disappear again.

**Comment by dceejay** [comment] 2019-05-21 14:21
I think we need a third opinion - My IOS 12.3 Iphone SE seems to still be fine. - both dark and light themes. Are you sure you don't have any other CSS overrides via any templates in play ?

**Comment by Harpau** [comment] 2019-05-21 14:41
Other CSS: No, at least not aware
I now tested theme "NODE-RED theme everywhere" - Style: Dark: This worked fine!
But maybe I got again caching problems: The Legends in the Chart Nodes are back again, no matter which Theme and Style I chose.

**Comment by dceejay** [comment] 2019-05-23 17:44
I'm still not able to replicate this. Nny further updates ?

**Comment by Harpau** [comment] 2019-05-24 08:07
Did you try to replicate this by adding an icon for the dashboard to the homescreen? The problem occurs on my iPhone and on my iPad, but only if you open the dashboard via an icon on the homescreen and only in the light (default) style.

**Comment by dceejay** [comment] 2019-05-24 08:55
Yeah - screenshot from my iphone having clicked th up arrow twice.
![image](https://user-images.githubusercontent.com/5375409/58315732-00d14c00-7e0a-11e9-821a-8dd2d8afeeef.png)

**Comment by Harpau** [comment] 2019-05-24 11:56
Ok, I will try it on a new IPhone over the weekend.

**Comment by Harpau** [comment] 2019-05-27 13:59
I tested it on the weekend on a new iphone and everything works fine there. 
The arrows do not disappear and the chart node does not display any legend.
It is obviously a caching problem when the dashboard is placed on the iphone on the home screen. 
I also tried everything to clear this cache, unfortunately without success. 
Somehow the iphone should be able to recognize that the data in the cache is invalid. 
Could it be that there have been some changes regarding case #480 to prevent this?

**Comment by dceejay** [comment] 2019-05-27 14:10
So I'm going to close this as this is no longer an issue.
480 has not been changed - we did to a test with it removed - but that then broke a lot of existing logins so was reverted quickly. You could remove the cache by removing the manifest= reference from the /dist/index.html file and deleting the appcache... not idea if that would make the home screen decide to drop it though... from the sound of what you are saying probably not, though there must be a way to really flush it. Maybe create a new home screen icon with a different name ?

**Closed by dceejay** 2019-05-27 14:10 UTC
