### ISSUE TITLE
Add ability to disable controls

### ISSUE THREAD

**Issue by jcwren** [node-red/node-red-dashboard#44] opened 2016-08-11 02:50 UTC
It would be handy to have a boolean 'disabled' property on the controls. Setting the disabled property would work similarly to the standard HTML disabled property, causing them to be greyed out.

I'm pretty sure this could be handled with a template block, but that gets a little complicated.

My particular desire is to be able to disable gauges and switches if the device goes offline. A one-shot timer is reset when data is received from the device, and if the timer expires, it would set the gauge and switch to a disabled state to reflect that.

**Comment by dceejay** [comment] 2016-08-11 09:54
Generally we prefer ideas on the google group or slack channel first to facilitate discussion. But ok to leave this here for now.

Not sure how this should be visualised. Ideally this should/could be a general pattern across any widget. The "obvious" one would be to grey out that particular widget, so would be part of theming etc. 

Of course there is also the question of should we indicate if the browser connection to the server breaks also...

**Comment by natcl** [comment] 2016-08-12 19:06
I'm not sure if this was removed but that was actually supported in
contrib-ui. There was a msg.disabled property that when set to True would
disable the widget (slider, button etc.) via the ng-disabled angular
property.

**Comment by jcwren** [comment] 2016-08-15 17:25
I gave this a try, by using an inject control, a function that was basically "delete msg.payload; msg.disabled = true; return msg;", and a control, but with no luck. Looking through the sources, I also didn't see anything that supported it directly.

**Comment by dceejay** [comment] 2016-08-15 18:40
@natcl - any pointers ? I can't see that in contrib-ui either ???

**Comment by natcl** [comment] 2016-08-15 18:48
In the widget it looks like this:
https://github.com/andrei-tatar/node-red-contrib-ui/blob/master/src/components/ui-component/templates/switch.html

And in the main code I think it's here:
https://github.com/andrei-tatar/node-red-contrib-ui/blob/c533d933c25dda5b501874177bfa59777ed7064e/ui.js#L105

**Comment by jcwren** [comment] 2016-08-15 18:57
So that would allow disabling a switch, but not a gauge, correct? As a gauge is not 'class="control-switch"' and not a boolean input.

**Comment by natcl** [comment] 2016-08-15 19:08
That particular code would work for angular widgets as is and would need to be adapter for more complex widgets like gauge.

**Comment by dceejay** [comment] 2016-08-15 19:16
ah @jcwren - so it was msg.enabled    - so try setting msg.enabled = false;   (boolean)

**Comment by natcl** [comment] 2016-08-15 19:18
I tried it over here and it seems like it was removed from the code either during the transition to dashboard or perhaps by andrei on his new branch

**Comment by dceejay** [comment] 2016-08-15 19:21
yeah - it's still half there.... 
Also it wouldn't work for buttons (as-is) as they have no input - so no way to set msg.enabled...

**Comment by natcl** [comment] 2016-08-15 19:22
Hmm the code still seems to be there, not sure why it wouldn't work.

**Comment by natcl** [comment] 2016-08-15 19:56
For reference:
seems to work with all angular widgets except the toggle.

**Comment by jcwren** [comment] 2016-08-16 12:19
Beautiful! That's working exactly as I need it to. Thank you :)

**Comment by matijagaspar** [comment] 2016-09-04 01:42
Still does not work correctly with switch widget.

**Comment by dceejay** [comment] 2016-09-04 09:56
HI - not sure what you mean - currently if it’s disabled then the user cannot change the state of the switch… if it is set by the flow then the state is still updated so the visual state reflects the real world state (and to allow you to preset the state). This is working as designed - (at least for me :-)

**Comment by dceejay** [comment] 2016-09-04 15:48
aha - it works ok on chrome but not on safari...

**Comment by dceejay** [comment] 2016-09-04 16:05
hmm - having done a clean restart  of all components... - it does seem to work ok on Chrome, Firefox and Safari... so closing again

**Closed by dceejay** 2016-09-04 16:05 UTC
Labels: enhancement
