### ISSUE TITLE
Add a date/picker

### ISSUE THREAD

**Issue by MarceloProjetos** [node-red/node-red-dashboard#56] opened 2016-09-07 22:08 UTC
Hi.

Please a like to know. Do you intend to make a datepicker object?

https://material.angularjs.org/latest/demo/datepicker

Thank you.

**Comment by dceejay** [comment] 2016-09-07 22:18
Probably :-)

Duplicate of Issue #14

**Closed by dceejay** 2016-09-07 22:18 UTC
Labels: duplicate
