### ISSUE TITLE
Chart blurring

### ISSUE THREAD

**Issue by Paul-Reed** [node-red/node-red-dashboard#380] opened 2018-04-10 19:12 UTC
I reported this issue in Slack 29th March, and several times since, but they are getting lost in the plethora of posts!

**Issue**
 3 charts displayed on one page, and for some reason the bottom chart is always displayed in a strange resolution. The chart labels, scale etc are blurred and large fonts, and the line is thick & blurred. (compare with chart above it).
It displays fine on Firefox, Edge, Mobile etc and problem seems confined to Chrome.
I've tried clearing cache, manifest, rebooting, and also tried swopping the charts around, but it  always applies to the bottom chart.

**To re-create issue**
I've attached a demo flow which highlights the issue, and which has been tried by another Slack contributor (Steve Rickus) who gets the same issue as reported.
To replicate the problem, load up the flow, let a few chart data points populate, then look in Chrome and you'll see 3 charts, if you then use F5 to reload the page and you should see the bottom chart become blurred (and stay blurred).

**Environment**
Google Chrome Version 65.0.3325.181 (Official Build) (64-bit) displayed on Windows 10 laptop.
Node-red v0.18.3 & dashboard v2.8.3 beta (git installed) running on RPi3, OS Raspbian Stretch.

![nr2](https://user-images.githubusercontent.com/973580/38577910-32ef788a-3cfa-11e8-90b5-fb81fe99e06b.PNG)

[testFlow.txt](https://github.com/node-red/node-red-dashboard/files/1896042/testFlow.txt)

**Comment by dceejay** [comment] 2018-04-10 19:15
duplicate of #302

**Comment by dceejay** [comment] 2018-04-13 12:33
closed by b369e2bec25c9169cd7a8a8f79c25a277519a1e5

**Closed by dceejay** 2018-04-13 12:33 UTC
Labels: duplicate
