### ISSUE TITLE
Chart does not delete old topic, when new stop arriving

### ISSUE THREAD

**Issue by Brian5600** [node-red/node-red-dashboard#342] opened 2018-01-16 20:58 UTC
I have some lines, which only get data once or stops getting data. The chart setting is to delete messages older than 12 hours. But the old points, which not get any new points, don't get deleted. After a day or two all times is fx 00:00 if HH:MM is the format on X-axis. After multiple days the last 12 hours is only a small part of the graph. I think it worked ok in some older version, but I am not sure.

I have also not tested, if it behave the same way, if one line which have got data continously, stops getting data, behave the same way.

**Comment by dceejay** [comment] 2018-01-17 08:37
Hi, trying to understand.. - you have data arriving on several topics ? one stops getting data... the other continues.... but the old data from the (non sending) feed doesn't disappear after the timeout period ? Is that it ?

**Comment by Brian5600** [comment] 2018-01-17 08:48
Hi Dave, exactly right, thanks for fast followup 
/Brian

**Comment by dceejay** [comment] 2018-01-17 08:52
hmm - so yes.. I guess it should be fixed... but then again it is a useful indication that you haven't been receiving data on that other channel... :-)

Fix in meantime is to have an inject node send a null every day at midnight (for example) to each topic to clear down that channel.

**Comment by Brian5600** [comment] 2018-01-17 09:42
Yes, you are right, it depends on what you want to show :-)

It might be a sollution, with the injektioner-node, but then you can never disable a Channel, without resetting the chart.

Thank you for following up.

**Comment by dceejay** [comment] 2018-01-17 09:45
Not sure if this is what you (also) want - but you can disable (hide) a channel from the chart by clicking on the channel name if you have the legend displayed.
![image](https://user-images.githubusercontent.com/5375409/35036056-0b675592-fb6b-11e7-8170-73b2a3df1e88.png)

**Comment by DeanCording** [comment] 2018-01-30 22:17
Hi Dave,

Here is an example of what happens
![stopped data](https://user-images.githubusercontent.com/251170/35594295-5aec653c-065e-11e8-8da0-a49d0a7603b4.png)

When setting up new data feeds, I often change the topic a few times.  In this case, the orange line on the left is data from a channel I renamed.  The blue line is the data after I renamed the channel.

Using the Persist node to preserve the graphs between restarts means that the only way to get rid of this data is the manually edit the Persist data file to delete the unwanted data.  If I don't then the graph just gets squashed up.

**Comment by dceejay** [comment] 2018-01-30 22:18
yup - fully aware.

**Comment by dceejay** [comment] 2018-01-30 22:24
The problem is that when data arrives on (say) topic A - then right now I have to iterate through the stored data for A in order to remove any old data... If I have to do that for every other topic performance will really suck (as if it wasn't bad enough already) when there are loads of topics to handle.

Of course an alternative would be for your persist node to dump old data also :-)

**Comment by DeanCording** [comment] 2018-01-30 22:30
The Persist node just saves the last message it receives and doesn't know or care about the contents.  Nice try but I can't fix it :-)

Can't you iterate from the bottom up - start checking the oldest first (of course this advice is offered without having looked at the code first)

**Comment by dceejay** [comment] 2018-01-30 22:37
that's exactly what the code does...
I will have another look at it (probably at the weekend)

Maybe the persist node ought to care :-)

**Comment by dceejay** [comment] 2018-01-30 22:50
ah - didn't realise the persist node only stores the one value... yeah makes sense now. Though now I have to ask why not just use a file out and in pair set to overwrite to do the same ?

**Comment by DeanCording** [comment] 2018-01-30 22:56
Because Persist allows you to save messages from a number of separate flows into the same file.  It also buffers the data to limit the amount of file I/O occurring, and automatically triggers as soon as the flows are ready (before the inject nodes trigger).

**Comment by dceejay** [comment] 2018-01-30 23:38
If you fancy looking at the code it's around line 195 of nodes/ui_chart.js and line 97 of src/components/ui-chart-js/ui-chart-js.js

**Closed** 2018-03-01 19:46 UTC
