### ISSUE TITLE
just upgraded dashboard to 2.26.0 and line chart stopped working. 

### ISSUE THREAD

**Issue by Alacritous** [node-red/node-red-dashboard#656] opened 2020-12-26 17:31 UTC
### What are the steps to reproduce?

The only change was upgrading to latest version. Both dashboard and Node-Red. I used the palette manager to perform the upgrade.

### What happens?

Dashboard line chart was working fine. Did the upgrade, now it's not displaying chart data I'm supplying. 

### What do you expect to happen?

Line chart display as before. 

### Please tell us about your environment:

- [ 2.26] Node-RED-Dashboard version:
- [ 1.2.6] Node-RED version:
- [ 10.21.0] node.js version:
- [6.14.10 ] npm version:
- [Ubuntu 19.10 ] Platform/OS:
- [Firefox 84.0.1 (64-bit) ] Browser:

I pull weather data from the weather API and parse forecast data from it and provide the chart control a JSON object of data that looks like the code below.  I double checked the documentation to see if you changed the required format and provided the control the example data that you provide on the documentation page and that didn't work either. 

```
[
	{
		"series": [
			"A"
		],
		"data": [
			[
				{
					"x": 1609005600000,
					"y": -6.42
				},
				{
					"x": 1609016400000,
					"y": -6.06
				},
				{
					"x": 1609027200000,
					"y": -6.86
				},
				{
					"x": 1609038000000,
					"y": -7.63
				},
				{
					"x": 1609048800000,
					"y": -7.77
				},
				{
					"x": 1609059600000,
					"y": -9.24
				},
				{
					"x": 1609070400000,
					"y": -9.32
				},
				{
					"x": 1609081200000,
					"y": -10
				},
				{
					"x": 1609092000000,
					"y": -8.54
				},
				{
					"x": 1609102800000,
					"y": -6.58
				},
				{
					"x": 1609113600000,
					"y": -8.73
				},
				{
					"x": 1609124400000,
					"y": -8.87
				},
				{
					"x": 1609135200000,
					"y": -8.18
				},
				{
					"x": 1609146000000,
					"y": -8.86
				},
				{
					"x": 1609156800000,
					"y": -8.82
				},
				{
					"x": 1609167600000,
					"y": -8.35
				},
				{
					"x": 1609178400000,
					"y": -6.04
				},
				{
					"x": 1609189200000,
					"y": -3.59
				},
				{
					"x": 1609200000000,
					"y": -7.95
				},
				{
					"x": 1609210800000,
					"y": -8.59
				},
				{
					"x": 1609221600000,
					"y": -9.72
				},
				{
					"x": 1609232400000,
					"y": -10.27
				},
				{
					"x": 1609243200000,
					"y": -11.21
				},
				{
					"x": 1609254000000,
					"y": -11.73
				},
				{
					"x": 1609264800000,
					"y": -8.9
				},
				{
					"x": 1609275600000,
					"y": -5.79
				},
				{
					"x": 1609286400000,
					"y": -8.89
				},
				{
					"x": 1609297200000,
					"y": -9.73
				},
				{
					"x": 1609308000000,
					"y": -10.36
				},
				{
					"x": 1609318800000,
					"y": -9.45
				},
				{
					"x": 1609329600000,
					"y": -10.33
				},
				{
					"x": 1609340400000,
					"y": -9
				},
				{
					"x": 1609351200000,
					"y": -6.43
				},
				{
					"x": 1609362000000,
					"y": -4.66
				},
				{
					"x": 1609372800000,
					"y": -8.67
				},
				{
					"x": 1609383600000,
					"y": -9.26
				},
				{
					"x": 1609394400000,
					"y": -9.74
				},
				{
					"x": 1609405200000,
					"y": -9.1
				},
				{
					"x": 1609416000000,
					"y": -8.33
				},
				{
					"x": 1609426800000,
					"y": -8.48
				}
			]
		],
		"labels": [
			""
		]
	}
]
```
This is what comes out the back end of the control after being supplied the above data.  which is the last two data pairs in the data I'm suppling to the control and this is what is displayed on the control.

```
{
	"series": [
		"A"
	],
	"data": [
		[
			{
				"x": 1609416000000,
				"y": -8.33
			},
			{
				"x": 1609426800000,
				"y": -8.48
			}
		]
	]
}

```
This is how the control appears now. I don't have a screen shot of if before. But it would show a chart with the ups and downs of the supplied data. 

![image](https://user-images.githubusercontent.com/1443724/103156394-70858680-4765-11eb-9e90-00cdcb0ce846.png)

**Comment by Alacritous** [comment] 2020-12-26 20:30
Okay,  got it working. 
![image](https://user-images.githubusercontent.com/1443724/103158736-6459f300-477e-11eb-8b50-c40a189dd9a1.png)


setting the X axis to display 40 points now shows the correct display. Was this a setting before the upgrade? I didn't change any settings when I upgraded. 

Now it displays as desired. 

![image](https://user-images.githubusercontent.com/1443724/103158720-252ba200-477e-11eb-9053-4ca67d68ac2e.png)

**Comment by dceejay** [comment] 2020-12-26 20:34
Odd. You shouldn’t have to set it. Does it now continue to work if you clear it ?

**Comment by Alacritous** [comment] 2020-12-26 20:37
I cleared the value and it shows 1000 kind of greyed in the entry field.  And it still works. 

![image](https://user-images.githubusercontent.com/1443724/103158803-64a6be00-477f-11eb-980a-bef532ab05c6.png)

**Comment by Alacritous** [comment] 2020-12-27 01:21
For completeness.  Below are two extracts from the configuration for the ui_chart. Before and after the upgrade. 

The difference between the two extracts is in the post upgrade there's a line about UTC time and the removeOIder and removeOlderPoints values are different.   

After the upgrade when the removeOlder was 1 and removeOlderPoints was 2 the display did not work.  But it did work with those values BEFORE the upgrade. 

This is the value NOW with the display apparently working properly.
++++++++++++++++++++++++++++++++++++++
   {
        "id": "deaefc0a.51ed88",
        "type": "ui_chart",
        "z": "60fd710c.4df468",
        "name": "",
        "group": "63b48458.2e2a2c",
        "order": 8,
        "width": 8,
        "height": 5,
        "label": "5 day forecast",
        "chartType": "line",
        "legend": "false",
        "xformat": "auto",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "0",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "useUTC": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "outputs": 1,
        "x": 800,
        "y": 550,
        "wires": [
            [
                "ea75155c.6f3e2"
            ]
        ]
    }

+++++++++++++++++++++++++++++++++++++++++++
This is the control config from a pre upgrade backup on Dec 23.  The display was working then with the values as shown.

   {
        "id": "deaefc0a.51ed88",
        "type": "ui_chart",
        "z": "60fd710c.4df468",
        "name": "",
        "group": "63b48458.2e2a2c",
        "order": 8,
        "width": 8,
        "height": 5,
        "label": "5 day forecast",
        "chartType": "line",
        "legend": "false",
        "xformat": "dd HH:mm",
        "interpolate": "linear",
        "nodata": "Data will appear soon",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "1",
        "removeOlderPoints": "2",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "useOldStyle": false,
        "outputs": 1,
        "x": 730,
        "y": 550,
        "wires": [
            []
        ]
    }


+++++++++++++++++++++++++++++++++++++++++++++++++++++
And I know the values were that way because here's the same configuration from a backup file from 2019. 

{
		"id": "deaefc0a.51ed88",
		"type": "ui_chart",
		"z": "60fd710c.4df468",
		"name": "",
		"group": "63b48458.2e2a2c",
		"order": 0,
		"width": "8",
		"height": "5",
		"label": "5 day forecast",
		"chartType": "line",
		"legend": "false",
		"xformat": "dd HH:mm",
		"interpolate": "linear",
		"nodata": "Data will appear soon",
		"dot": false,
		"ymin": "",
		"ymax": "",
		"removeOlder": "1",
		"removeOlderPoints": "2",
		"removeOlderUnit": "3600",
		"cutout": 0,
		"useOneColor": false,
		"colors": [
			"#1f77b4",
			"#aec7e8",
			"#ff7f0e",
			"#2ca02c",
			"#98df8a",
			"#d62728",
			"#ff9896",
			"#9467bd",
			"#c5b0d5"
		],
		"useOldStyle": false,
		"outputs": 1,
		"x": 720,
		"y": 300,
		"wires": [
			[]
		]
	}

**Comment by dceejay** [comment] 2020-12-29 10:02
I have no explanation for how those values could change. I was imagining that if they had been blank or 0 we may have "accidentally" inserted some "real" values - but as they were already 1 and 2 then there is nothing in the code to change them.

**Comment by Alacritous** [comment] 2020-12-29 19:13
No, the values never changed. It just stopped working with those values. when I did the upgrade, those values were in place and it started showing only 2 values. Which is why I after much scratching of my head I changed the value to 40(which is the number of samples returned that I fed to the chart) and it displayed all the values. and then when there's no value supplied to the field, it defaults to 1000(as shown by the greyed value in the blank field) and shows all the values given. 

Something changed to make the control pay attention to the value given in that field. 

Don't get me wrong, I got it working, I'm not upset or anything. Just trying to fill in the gaps.

**Comment by dceejay** [comment] 2020-12-30 10:59
Yeah - me too..(trying to understand)... hmm so originally it was set to 1 and 2 - and was actually ignoring that and showing all 40 values... - so actually the previous behaviour was wrong - so yes - it was a bug and was "fixed".... even though it broke you :-)... Ok going to close this as I think it is now working as designed (or intended)

**Closed by dceejay** 2020-12-30 10:59 UTC

**Comment by Alacritous** [comment] 2020-12-30 17:13
What's been messing me up is the labeling of those fields.  Both in the interface and the config JSON. What are they supposed to do?

**Comment by dceejay** [comment] 2020-12-30 20:33
RemoveOlder is the number of time units (removeOlderUnits) in seconds after which points get removed automatically.  So 1x 3600 = 1 hour. RemoveOlderPoints is the maximum number of points to display. So 2 would/should only show 2 points not your whole set. The two concepts can be combined so it can be limited by both time and number.
